import Button from "@mui/material/Button";
import CssBaseline from "@mui/material/CssBaseline";
import TextField from "@mui/material/TextField";
import { useState, useEffect, useContext } from "react";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import Paper from "@mui/material/Paper";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Landing from "../assets/landing2.png";
import BrandLogo from "../assets/brand-logo.png";
import { NavLink } from "react-router-dom";
import { SuccessContext } from "../context/success-context";
import Snackbar from "@mui/material/Snackbar";
import { Alert } from "@mui/material";
import axios from "axios";
import { useNavigate } from "react-router";
// import CryptoJS from "crypto-js";
import { setUser } from "../functions/user-management";

function Copyright(props) {
  return (
    <Typography
      variant="body2"
      color="text.secondary"
      align="center"
      {...props}
    >
      {"Copyright © "}
      CodeRoom {new Date().getFullYear()}
      {". "}Created by Matthew Fung
    </Typography>
  );
}

const defaultTheme = createTheme();

export default function LoginPage() {
  const { success, setSuccess } = useContext(SuccessContext);
  const navigate = useNavigate();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errors, setErrors] = useState({});

  // Sets the page title
  useEffect(() => {
    document.title = "Login"; // Set the desired page title
    return () => {
      document.title = "CodeRoom"; // Reset the title when the component unmounts
    };
  }, []);

  // Handles form submission
  const handleSubmit = async (event) => {
    event.preventDefault();

    const formErrors = {};
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    // check if email is empty
    if (!email) {
      formErrors.email = "Email is required";
    }
    // check if given email is in valid format
    if (!emailRegex.test(email)) {
      formErrors.email = "Invalid Email format";
    }
    // check if password is empty
    if (!password) {
      formErrors.password = "Password is required";
    }

    // Set errors or submit the form
    if (Object.keys(formErrors).length > 0) {
      setErrors(formErrors);
    } else {
      // submit the information to api to create an account
      try {
        // submit to api to create account
        // redirect user to main page
        const loginPayload = { email, password };
        const response = await axios.post(
          "http://localhost:5001/api/user/login",
          loginPayload
        );
        const user = response.data;
        // const key = import.meta.env.JWT_ENCRYPT_KEY;
        // const securedToken = CryptoJS.AES.encrypt(user.token, key).toString();
        // console.log(securedToken);

        setUser(user.name, user.email, user.token);
        navigate(`/main/overview`);
      } catch (error) {
        console.log(error);

        formErrors.login = "Login Failed. Please try again.";
        setErrors(formErrors);
      }
    }
  };

  return (
    <ThemeProvider theme={defaultTheme}>
      <Grid container component="main" sx={{ height: "100vh" }}>
        {/* Reset Default CSS styling */}
        <CssBaseline />
        {/* Landing Image */}
        <Grid
          item
          xs={false}
          sm={4}
          md={6}
          lg={8}
          sx={{
            backgroundImage: `url(${Landing})`,
            backgroundRepeat: "no-repeat",
            backgroundColor: (t) =>
              t.palette.mode === "light"
                ? t.palette.grey[50]
                : t.palette.grey[900],
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        ></Grid>
        <Grid
          item
          xs={12}
          sm={8}
          md={6}
          lg={4}
          component={Paper}
          elevation={6}
          square
          className="flex flex-col items-center justify-center"
        >
          {/* Login Form */}
          <Box
            sx={{
              my: 8,
              mx: 4,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Box className="w-14 h-14 my-5">
              <img
                src={BrandLogo}
                alt="CodeRoom Logo - Generated By StableDiffusion"
              />
            </Box>
            <Typography component="h1" variant="h5">
              Welcome To CodeRoom
            </Typography>
            <Box
              component="form"
              noValidate
              onSubmit={handleSubmit}
              sx={{ mt: 1 }}
            >
              <TextField
                margin="normal"
                required
                fullWidth
                id="email"
                label="Email Address"
                name="email"
                autoFocus
                autoComplete="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                error={errors.email != undefined}
                helperText={errors.email}
              />
              <TextField
                margin="normal"
                required
                fullWidth
                name="password"
                label="Password"
                type="password"
                id="password"
                autoComplete="current-password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                error={errors.password != undefined}
                helperText={errors.password}
              />
              {/* <FormControlLabel
                control={<Checkbox value="remember" color="primary" />}
                label="Remember me"
              /> */}
              <Button
                type="submit"
                fullWidth
                variant="contained"
                sx={{ mt: 3, mb: 2 }}
              >
                Sign In
              </Button>
              {errors.login && (
                <Typography className=" text-red-500 text-xs" sx={{ mb: 1 }}>
                  {errors.login}
                </Typography>
              )}

              <NavLink
                to="/create-account"
                className={(isActive) => (isActive ? "active" : "")}
              >
                <div className="text-sm underline">
                  Don&#39;t have an account?
                </div>
              </NavLink>
              <Copyright sx={{ mt: 5 }} />
            </Box>
          </Box>
          {/* Snack Bar */}
          <Snackbar
            anchorOrigin={{ vertical: "bottom", horizontal: "right" }}
            open={success}
            autoHideDuration={6000}
            onClose={() => {
              setSuccess(false);
            }}
          >
            <Alert
              onClose={() => {
                setSuccess(false);
              }}
              severity="success"
              sx={{ width: "100%" }}
            >
              Create Account Successful
            </Alert>
          </Snackbar>
        </Grid>
      </Grid>
    </ThemeProvider>
  );
}
